export { default as LandingPage } from './LandingPage'
export {default as Login } from './Login'
export { default as Signup } from './Signup'
export { default as Solutions } from './Solutions'
export { default as Industries } from './Industries'
export { default as Resources } from './Resources'
export { default as WorkerSettings } from './WorkerSettings'
export { default as TestPage } from './TestPage'
